### ISSUE TITLE
Improve audio synthesis

### ISSUE THREAD

**Issue by asigalov61** [stevenwaterman/musetree#85] opened 2020-07-30 13:41 UTC
Hey guys,

Thank you all so much for MuseTree - its a dream come true :)

But you simply must replace the SoundFont ASAP !!! I AM BEGGING YOU !!! 

The SoundFont is horrible and it kills the software and literally makes me dizzy. I have 10 years of classical music training/experience so please trust me on this one.

The best solution I would recommend is fluidsynth. (see my repos)

Google Colabs use it for demonstrations all the time. It's compact (like 60? or 80MB?) or find something small.  I can try to post the working Python code but do let me know. But ideally, I would run small full general midi font on the frontend of the user.

Anything but what is there right now. It's not fun :(

Nice full and relatively size-sane fonts can be found here
https://sites.google.com/site/soundfonts4u/

Thank you so much and please help because I really want to use and love MuseTree. I also do not want your work to go to waste or be unappreciated.

Sincerely,

AS

**Comment by asigalov61** [comment] 2020-07-30 15:02
Here is one other possible solution:

This: http://gleitz.github.io/midi-js-soundfonts/

And this: https://github.com/gleitz/MIDI.js

**Comment by stevenwaterman** [comment] 2020-07-30 15:29
Closing as duplicate of https://github.com/stevenwaterman/musetree/issues/80. I have added a link to this issue on that one.

Also, please use a descriptive title and don't use all caps

**Closed by stevenwaterman** 2020-07-30 15:29 UTC
