### ISSUE TITLE
Import Midi Not Respecting File Tempo

### ISSUE THREAD

**Issue by farfromsubtle** [stevenwaterman/musetree#46] opened 2020-05-23 14:22 UTC
So far I have been unsuccessful at importing midi except for ones generated by musetree itself.

It seems that if I export from a DAW the notes are intact when imported to musetree but the tempo is slowed down drastically (I would guess around 50 bpm).

I even tried using mrcheeze's provided base midi to create my import with the same issue.

I exported from both Studio One and Logic Pro with the same effect.

Example attached.

[base styx.mid.zip](https://github.com/stevenwaterman/musetree/files/4671912/base.styx.mid.zip)

**Comment by stevenwaterman** [comment] 2020-05-23 17:35
Closing as duplicate of #42

**Closed by stevenwaterman** 2020-05-23 17:35 UTC
