### ISSUE TITLE
right click doesnt do anything?

### ISSUE THREAD

**Issue by cringegaming64** [stevenwaterman/musetree#83] opened 2020-06-28 02:32 UTC
when i open up muse tree, i right click on the root, and it does nothing, i try again multiple times, i refresh my page, and it still does nothing, i close out of my browser and try again, i even restart my computer to no avail. it seems that muse tree it does not respond to input that i give it. everything else seems to work fine but this one bug that makes it impossible to use it

**Comment by stevenwaterman** [comment] 2020-06-28 12:04
Confirmed there is a bug in Chrome, right-clicking the root node makes the context menu appear in the wrong place, to the right of the actual node. It could appear off the screen. Does that sound like what's happening to you? I'll try and fix it today.

**Comment by stevenwaterman** [comment] 2020-06-28 15:07
After playing with it more, the problem is worse when the window is wider. When full-screen, i can't see the context menu.

**Comment by stevenwaterman** [comment] 2020-06-28 20:35
Fixed in v2.19.5

**Closed by stevenwaterman** 2020-06-28 20:35 UTC
Labels: High Priority, bug

**Comment by FlashlightET** [comment] 2021-08-14 00:25
still happening

**Comment by stevenwaterman** [comment] 2021-08-15 18:04
Just tested it in Chrome - works for me. Could you create a new issue with more information about your particular setup & steps to reproduce?
